heat_template_version: ocata
description: >
  This stack is an example how to set up a main_server with latency and bandwidthexpectations,
  then how to create an additional server depending on the first one.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.

resources:
  main_server:
    type: OS::NetworkAware::Server
    properties:
      image: cirros
      flavor: test-flavor
      networks:
      - network: { get_param: NetID }
      expected_bandwidth:
        - { to_host: node-2, bandwidth: 10_000 }
      maximum_latency:
        - { to_host: node-2, latency: 30 }
  secondary_server:
    type: OS::NetworkAware::Server
    depends_on: main_server
    properties:
      image: cirros
      flavor: test-flavor
      networks:
      - network: { get_param: NetID }
      expected_bandwidth:
        - { to_host: { get_attr: [ main_server, host ] }, bandwidth: 10_000 }
      maximum_latency:
        - { to_host: { get_attr: [ main_server, host ] }, latency: 20 }


outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ main_server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ main_server, first_address ] }

