heat_template_version: ocata
description: Launch a basic instance with CirrOS image using the
             ``m1.tiny`` flavor, ``mykey`` key,  and one network.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.

resources:
  main_server:
    type: OS::NetworkAware::Server
    properties:
      image: cirros
      flavor: test-flavor
      networks:
      - network: { get_param: NetID }
      expected_bandwidth:
        - { to_host: node-2, bandwidth: 99 }
        - { to_host: node-3, bandwidth: 120 }
      maximum_latency:
        - { to_host: node-2, latency: 500 }
        - { to_host: node-2, latency: 501 }
  secondary_server:
    depends_on: main_server
    properties:
      image: cirros
      flavor: test-flavor
     expected_bandwidth:
        - { to_host: get_attr: [ main_server, host ], bandwidth: 1000 }
        - { to_host: gateway-5, bandwidth: 120 }
      maximum_latency:
        - { to_host: get_attr: [ main_server, host ], latency: 20 }
        - { to_host: gateway-5, latency: 112 }

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ main_server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ main_server, first_address ] }

